# Generated by Django 4.1.7 on 2023-05-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0003_cars_price_cars_title_condition_cars_vin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='title_condition',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('SALVAGE', 'Salvage'), ('DISTRACTION', 'Distraction')], default='Clean', max_length=11),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vin_number',
            field=models.CharField(default='00', max_length=17),
        ),
        migrations.CreateModel(
            name='RemoveParts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rims', models.IntegerField()),
                ('tires', models.IntegerField()),
                ('engine', models.BooleanField()),
                ('catalyst', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars')),
            ],
        ),
    ]
