# Generated by Django 4.1.7 on 2023-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0004_alter_cars_title_condition_alter_cars_vin_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='car',
        ),
        migrations.AddField(
            model_name='junkcars',
            name='date_out',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='junkcars',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parts',
            name='car_i_n',
            field=models.CharField(default='Inventary', max_length=15),
        ),
    ]
