# Generated by Django 4.1.7 on 2023-05-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0005_remove_parts_car_junkcars_date_out_junkcars_out_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='part_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='car_i_n',
        ),
        migrations.AddField(
            model_name='parts',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventary.cars'),
        ),
    ]
