# Generated by Django 4.1.7 on 2023-05-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0006_rename_part_name_parts_name_remove_parts_car_i_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldParts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('part_type', models.CharField(choices=[('Tires', 'Tires'), ('Rims', 'Rims'), ('Engines', 'Engines'), ('Catalyst', 'Catalyst'), ('Others', 'Others')], max_length=8)),
                ('sold_date', models.DateField()),
                ('add_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.buyers')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventary.cars')),
            ],
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
    ]
