# Generated by Django 4.1.7 on 2023-05-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0007_soldparts_delete_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tires', models.IntegerField()),
                ('rims', models.IntegerField()),
                ('catalysts', models.IntegerField()),
                ('engines', models.IntegerField()),
                ('scratched_cars', models.IntegerField()),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
