# Generated by Django 4.1.7 on 2023-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0008_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='catalysts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='engines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='rims',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='scratched_cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tires',
            field=models.IntegerField(default=0),
        ),
    ]
