# Generated by Django 4.1.7 on 2023-06-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0009_alter_stock_catalysts_alter_stock_engines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
