# Generated by Django 4.1.7 on 2023-06-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0010_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='price',
            new_name='cost',
        ),
    ]
