# Generated by Django 4.1.7 on 2023-06-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0011_rename_price_cars_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/cars/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.FileField(blank=True, null=True, upload_to='media/titles/'),
        ),
    ]
