# Generated by Django 4.1.7 on 2023-07-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0012_alter_cars_image_alter_cars_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='soldparts',
            name='part_type',
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.buyers')),
            ],
        ),
    ]
