# Generated by Django 4.1.7 on 2023-07-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0013_parttype_remove_soldparts_part_type_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldparts',
            name='part_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventary.parttype'),
            preserve_default=False,
        ),
    ]
