# Generated by Django 4.1.7 on 2023-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0015_partsbyinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='parts_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
